#!/bin/sh

# Run STACS, and stash the output for analysis by the Github integration.
stacs \
    --rule-pack /mnt/stacs/rules/credential.json \
    --cache-directory /mnt/stacs/cache \
    "/mnt/stacs/input/${SCAN_SUBDIR}" 1> /tmp/stacs.sarif

# Run the Github integration.
if [ "${SCAN_SUBDIR}x" != "x" ]; then
    python3 -m stacs.ci.github /tmp/stacs.sarif --prefix "${SCAN_SUBDIR}"
else
    python3 -m stacs.ci.github /tmp/stacs.sarif
fi

# Fail the build on unsuppressed finding, if requested.
STATUS=$?
FAIL_BUILD="$(echo ${FAIL_BUILD} | tr '[A-Z]' '[a-z]')"

if [ "${FAIL_BUILD}" == "true" ]; then
    exit $STATUS
else
    exit 0
fi
